export const characterAndDress = {
  walk: {
    spritLength: 15,
    cap: 'cap',
    catEar: 'catEar',
    character: 'character',
    cheek: 'cheek',
    leaf: 'leaf',
    mouseEar: 'mouseEar',
    mouseTail: 'mouseTail',
    necktie: 'necktie',
    nose: 'nose',
  },
  apple: {
    spritLength: 15,
    bag: 'bag',
    cap: 'cap',
    catEar: 'catEar',
    character: 'character',
    cheek: 'cheek',
    leaf: 'leaf',
    mouseEar: 'mouseEar',
    mouseTail: 'mouseTail',
    necktie: 'necktie',
    nose: 'nose',
  },
  surprised: {
    spritLength: 28,
    cap: 'cap',
    catEar: 'catEar',
    character: 'character',
    cheek: 'cheek',
    leaf: 'leaf',
    mouseEar: 'mouseEar',
    mouseTail: 'mouseTail',
    necktie: 'necktie',
    nose: 'nose',
  },
  sit: {
    spritLength: 15,
    bag: 'bag',
    cap: 'cap',
    catEar: 'catEar',
    character: 'character',
    cheek: 'cheek',
    leaf: 'leaf',
    mouseTail: 'mouseTail',
    necktie: 'necktie',
    nose: 'nose',
  },
};
