export const displayElements = {
  tweetButton: document.getElementById('tweetButton'),
  navigationBar: document.getElementById('navigationBar'),
  tweetWindow: document.getElementById('tweetWindow'),
  bottleWindow: document.getElementById('bottleWindow'),
  characterDressUpWindow: document.getElementById('characterDressUpWindow'),
  islandDressUpWindow: document.getElementById('islandDressUpWindow'),
};
export const displayData = {
  default: {
    tweetButton: true,
    navigationBar: true,
    tweetWindow: false,
    bottleWindow: false,
    characterDressUpWindow: false,
    islandDressUpWindow: false,
  },
  tweet: {
    tweetButton: false,
    navigationBar: true,
    tweetWindow: true,
    bottleWindow: false,
    characterDressUpWindow: false,
    islandDressUpWindow: false,
  },
  bottle: {
    tweetButton: false,
    navigationBar: true,
    tweetWindow: false,
    bottleWindow: true,
    characterDressUpWindow: false,
    islandDressUpWindow: false,
  },
  characterDressUp: {
    tweetButton: false,
    navigationBar: false,
    tweetWindow: false,
    bottleWindow: false,
    characterDressUpWindow: true,
    islandDressUpWindow: false,
  },
  islandDressUp: {
    tweetButton: false,
    navigationBar: false,
    tweetWindow: false,
    bottleWindow: false,
    characterDressUpWindow: false,
    islandDressUpWindow: true,
  },
};
